import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from './router';
import { Component, Fragment, createContext, useCallback, useContext, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import {
  Archive, ArrowDownToLine, ArrowLeft, ArrowRight, Bell, Check, CheckCircle2, ChevronDown, CircleAlert,
  CodeXml, CreditCard, FileText, FolderOpen, FolderKanban, Globe2, GraduationCap, HelpCircle, LayoutTemplate, LoaderCircle, Mail, Search,
  LockKeyhole, LogOut, Menu, MessageCircle, Moon, Paperclip, PanelLeftClose,
  PanelLeftOpen, PanelRightClose, PanelRightOpen, Plus, Save, Send, Settings2,
  ShieldCheck, SlidersHorizontal, Sparkles, Sun, Trash2, UploadCloud, X,
  ChevronRight, Database, Eye, GripVertical, Keyboard, MoreHorizontal, Pencil, Pin, PinOff, UserRound, Volume2, BellRing, Shield, Sliders, Monitor, Palette, Languages, CircleUserRound, LogOut as LogOutIcon, LayoutDashboard, Users, AlertTriangle, ClipboardList, Megaphone, RefreshCw, MessageSquareText, Activity, FileCog,
  Copy, Share2, ThumbsDown, ThumbsUp, Upload,
} from 'lucide-react';
import { api, clearCsrfToken, download, setCsrfToken } from './api';
import { departments, programs } from './data';
import '@fontsource-variable/plus-jakarta-sans';
import '@fontsource/dm-mono/400.css';
import '@fontsource/dm-mono/500.css';
import './styles.css';
import LandingPage from './Landing';
import { FeatureUpdatesAdmin, ProductUpdatePopup } from './FeatureUpdates';
import { renderAsync as renderDocx } from 'docx-preview';
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';

const AppContext = createContext(null);

const I18nContext = createContext({ language: 'id', t: (value) => value });
const textNodeOriginals = new WeakMap();
const textNodeRendered = new WeakMap();
const attributeOriginals = new WeakMap();
const attributeRendered = new WeakMap();

const EN_UI = {
  'Chat baru': 'New chat',
  'Chats': 'Chats',
  'Dokumen': 'Documents',
  'Recents': 'Recents',
  'Disematkan': 'Pinned',
  'Belum dikelompokkan': 'Ungrouped',
  'Bantuan': 'Help',
  'Feedback': 'Feedback',
  'Settings': 'Settings',
  'Keluar': 'Log out',
  'Log out': 'Log out',
  'Upgrade plan': 'Upgrade plan',
  'Personalisasi': 'Personalization',
  'Jurusan & prodi': 'Department & program',
  'Akun Laprakin': 'Laprakin account',
  'Workspace pribadi': 'Personal workspace',
  'General': 'General',
  'Notifications': 'Notifications',
  'Personalization': 'Personalization',
  'Billing': 'Billing',
  'Data controls': 'Data controls',
  'Storage': 'Storage',
  'Safety': 'Safety',
  'Security and login': 'Security and login',
  'Keyboard': 'Keyboard',
  'Appearance': 'Appearance',
  'Contrast': 'Contrast',
  'Accent color': 'Accent color',
  'Language': 'Language',
  'Light': 'Light',
  'Dark': 'Dark',
  'System': 'System',
  'Default': 'Default',
  'High': 'High',
  'Bahasa Indonesia': 'Bahasa Indonesia',
  'English': 'English',
  'Compact workspace': 'Compact workspace',
  'Rapatkan jarak dan komponen di workspace.': 'Use tighter spacing and compact components in the workspace.',
  'Proses dokumen': 'Document processing',
  'Deadline laprak': 'Report deadline',
  'Update produk': 'Product updates',
  'Gaya bahasa': 'Writing style',
  'Sudut pandang': 'Perspective',
  'Struktur awal': 'Default structure',
  'Instruksi tambahan': 'Additional instructions',
  'Billing & QRIS': 'Billing & QRIS',
  'Current plan': 'Current plan',
  'Pilih plan': 'Choose a plan',
  'Pilih kebutuhanmu.': 'Choose what you need.',
  'Plan aktif': 'Current plan',
  'Pilih Pro': 'Choose Pro',
  'Pilih Max': 'Choose Max',
  'Dipilih': 'Selected',
  'Bayar dengan QRIS': 'Pay with QRIS',
  'Refresh status': 'Refresh status',
  'Kembali ke workspace': 'Back to workspace',
  'History transaksi': 'Transaction history',
  'Riwayat akun': 'Account history',
  'Muat ulang': 'Reload',
  'Belum ada transaksi.': 'No transactions yet.',
  'Buka Billing': 'Open Billing',
  'Kelola billing di halaman khusus.': 'Manage billing on a dedicated page.',
  'Chat disematkan.': 'Chat pinned.',
  'Chat dilepas dari sematan.': 'Chat unpinned.',
  'Chat diarsipkan.': 'Chat archived.',
  'Chat dihapus permanen.': 'Chat permanently deleted.',
  'Ubah nama': 'Rename',
  'Pindahkan ke folder': 'Move to folder',
  'Folder baru': 'New folder',
  'Pin chat': 'Pin chat',
  'Lepas pin': 'Unpin chat',
  'Arsip': 'Archive',
  'Hapus': 'Delete',
  'Konfigurasi': 'Configuration',
  'Konfigurasi chat': 'Chat configuration',
  'Simpan': 'Save',
  'Muat dokumen kerja...': 'Loading working document...',
  'Buat laprak': 'Create report',
  'Export Word': 'Export Word',
  'Unduh': 'Download',
  'Kirim': 'Send',
  'Tambah bahan': 'Add material',
  'Jenis bahan': 'Material type',
  'Modul / artikel': 'Module / article',
  'Screenshot / bukti': 'Screenshot / evidence',
  'Template': 'Template',
  'Data': 'Data',
  'Tulis tugasmu, tempel link, atau paste gambar...': 'Write your task, paste a link, or paste an image...',
  'Tambahkan pesan untuk bahan ini...': 'Add a message for these materials...',
  'Enter untuk kirim Â· Shift + Enter untuk baris baru Â· file hanya terlihat di akunmu': 'Enter to send Â· Shift + Enter for a new line Â· files are private to your account',
  'Notifikasi': 'Notifications',
  'Tandai semua dibaca': 'Mark all as read',
  'Semua sudah dibaca': 'All caught up',
  'Belum ada notifikasi.': 'No notifications yet.',
  'Tutup': 'Close',
  'Buat chat laprak dulu.': 'Create a report chat first.',
  'Mulai dengan teks, bahan, atau link yang kamu punya.': 'Start with any text, materials, or links you have.',
  'Chat Laprakin': 'Laprakin chat',
  'Dokumen kerja': 'Working document',
  'Dokumen ini belum memiliki ruang chat yang bisa dibuka.': 'This document does not yet have a chat room that can be opened.',
  'Refresh': 'Refresh',
  'Cari judul, mata kuliah, atau modul': 'Search title, course, or module',
  'Buka chat': 'Open chat',
  'mau laprakin apa hari ini,': 'what would you like to Laprakin today,',
  'Tulis mata kuliah dan materinya sekali. Laprakin akan menangkap brief, lalu menanyakan hanya yang benar-benar kurang.': 'Mention the course and topic once. Laprakin will capture the brief and only ask for what is truly missing.',
  'Siapkan identitas cover': 'Set up cover identity',
  'Opsional sekarang. Disimpan sekali dan otomatis dipakai pada laprak berikutnya.': 'Optional for now. Save it once and reuse it on future reports.',
  'Nama lengkap': 'Full name',
  'Nomor mahasiswa': 'Student number',
  'Nanti': 'Later',
  'Deteksi otomatis': 'Auto-detect',
  'Brief tertangkap': 'Brief captured',
  'Acuan dan ketentuan': 'Sources and requirements',
  'Buat folder baru': 'Create new folder',
  'Nama folder baru': 'New folder name',
  'Pilih jurusan': 'Choose department',
  'Pilih prodi': 'Choose program',
  'Formal': 'Formal',
  'Semi-formal': 'Semi-formal',
  'Saya': 'I',
  'Kita': 'We',
  'Impersonal': 'Impersonal',
  'Berbasis langkah': 'Step-based',
  'Berbasis pengujian': 'Testing-based',
  'Berbasis proyek': 'Project-based',
  'Gratis': 'Free',
  'Credit tersedia': 'Available credits',
  'Tidak berlangganan': 'Not subscribed',
  'Status': 'Status',
  'Menunggu pembayaran. Scan QRIS yang muncul di checkout Midtrans.': 'Waiting for payment. Scan the QRIS shown in Midtrans checkout.',
  'Pembayaran berhasil. Credit atau plan telah diaktifkan oleh server.': 'Payment successful. Credits or plan were activated by the server.',
  'Pembayaran ditolak. Pilih checkout QRIS baru bila ingin mencoba lagi.': 'Payment was declined. Create a new QRIS checkout to try again.',
  'Kode QRIS sudah kedaluwarsa. Buat checkout QRIS baru.': 'The QRIS code has expired. Create a new QRIS checkout.',
  'Checkout dibatalkan. Belum ada credit atau plan yang ditambahkan.': 'Checkout was cancelled. No credits or plan were added.',
  'Gateway belum aktif': 'Gateway unavailable',
  'Pembayaran aman melalui QRIS Dinamis Midtrans.': 'Secure payment through Dynamic QRIS Midtrans.',
  'Pilih paket yang sesuai ritme belajarmu.': 'Choose the plan that fits your study rhythm.',
  'Plan untuk kebutuhan praktikum yang rutin.': 'A plan for regular practical coursework.',
  'Plan untuk semester padat dan revisi intensif.': 'A plan for busy semesters and intensive revisions.',
  'Mulai dan pahami alur kerja Laprakin.': 'Start and learn the Laprakin workflow.',
};


Object.assign(EN_UI, {
  'Perbandingan dokumen': 'Document comparison',
  'Bandingkan hasilnya.': 'Compare the results.',
  'Lihat perbedaan alur, kelengkapan pembahasan, dan kerapian hasil dari dua dokumen yang mengerjakan konteks praktikum yang sama.': 'See the difference in flow, completeness, and document polish for the same practical-work context.',
  'Pilih mode untuk melihat perbandingan Laprakin yang sesuai.': 'Choose a mode to view the matching Laprakin comparison.',
  'Perbandingan mode': 'Mode comparison',
  'Geser atau scroll dokumen untuk melihat detailnya.': 'Swipe or scroll the documents to see the details.',
  'Masuk': 'Sign in',
  'Coba gratis': 'Try for free',
  'Layanan': 'Services',
  'Perbedaan': 'Compare',
  'Tutorial': 'Tutorial',
  'Harga': 'Pricing',
  'Ceritakan tugasmu atau paste gambar di sini...': 'Describe your task or paste an image here...',
  'Lampirkan file': 'Attach file',
  'Punya modul & bukti': 'I have a module & evidence',
  'Hanya teks': 'Text only',
  'Lihat perbedaan': 'See the comparison',
  'Scroll untuk lanjut': 'Scroll to continue',
  'Muat ulang halaman untuk melanjutkan.': 'Reload the page to continue.',
  'Halaman sedang dimuat ulang dengan aman.': 'The page is being safely reloaded.',
  'Tampilan tidak dapat dimuat.': 'This view could not be loaded.',
  'Kembali ke beranda': 'Back to homepage',
  'Daftar': 'Sign up',
  'Masuk dengan Google': 'Sign in with Google',
  'Lupa kata sandi?': 'Forgot password?',
  'Buat akun': 'Create account',
  'Email': 'Email',
  'Kata sandi': 'Password',
  'Nama lengkap': 'Full name',
  'Verifikasi email': 'Verify email',
  'Kirim ulang email': 'Resend email',
  'Buat chat laprak dulu.': 'Create a report chat first.',
  'Panel ini baru dipakai untuk mengubah konteks tugas yang sedang dibuka.': 'This panel is used to change the context of the open task.',
  'Hanya untuk laprak ini.': 'Only for this report chat.',
  'Nama laprak': 'Report name',
  'Mata kuliah': 'Course',
  'Modul atau konteks': 'Module or context',
  'Jenis struktur': 'Structure type',
  'Struktur prodi': 'Program structure',
  'Dipakai otomatis.': 'Applied automatically.',
  'Struktur khusus': 'Custom structure',
  'Hanya bila tugas berbeda.': 'Only for a different task format.',
  'Susunan bagian': 'Section order',
  'Simpan konfigurasi': 'Save configuration',
  'Jurusan, prodi, gaya penulisan, dan billing ada di Settings. Dark mode bisa diubah dari header workspace.': 'Department, program, writing preferences, and billing are in Settings. Dark mode can be changed from the workspace header.',
  'Ringkas konteks tugas.': 'Summarize the task context.',
  'Opsional bila bahan file belum cukup menjelaskan tugas.': 'Optional when uploaded materials do not fully explain the task.',
  'Modul / topik': 'Module / topic',
  'Permintaan dosen': 'Instructor request',
  'Tambah modul / paper / screenshot': 'Add module / paper / screenshot',
  'Tambahkan file bila perlu.': 'Add files if needed.',
  'Siap membuat dokumen kerja?': 'Ready to create a working document?',
  'Semua bahan dan konteks chat ini akan dipakai sebagai titik awal.': 'All materials and chat context will be used as a starting point.',
  'Analisis': 'Analyze',
  'Susun draft': 'Create draft',
  'Susun ulang': 'Regenerate',
  'Pilih atau upgrade plan dari halaman harga. Riwayat pembayaran disimpan di Settings ini.': 'Choose or upgrade a plan from the pricing page. Payment history is stored in these settings.',
  'Lihat plan': 'View plans',
  'Memuat riwayat...': 'Loading history...',
  'Plan dan riwayat transaksi.': 'Plan and transaction history.',
  'Plan dasar': 'Base plan',
  'Mulai gratis': 'Start free',
  'Individual': 'Individual',
  'Pilih plan yang pas untukmu.': 'Choose the plan that fits you.',
  'Pilih plan yang tepat untukmu.': 'Choose the plan that is right for you.',
  'Mulai dari kebutuhan praktikum harian, lalu naikkan kapasitas saat ritme belajarmu bertambah.': 'Start with daily coursework, then increase capacity as your workload grows.',
  'Kembali': 'Back',
  'Cari chat': 'Search chats',
  'Cari settings': 'Search settings',
  'Mulai tanpa biaya': 'Start at no cost',
  'Untuk laprak harian': 'For everyday reports',
  'Untuk semester padat': 'For busy semesters',
  'Pembayaran QRIS baru dimulai setelah login.': 'QRIS payment starts after you sign in.',
  'Naikkan kapasitas Laprakin saat kamu membutuhkannya.': 'Increase Laprakin capacity when you need it.',
  'Checkout QRIS': 'QRIS checkout',
  'Menghitungâ€¦': 'Calculatingâ€¦',
  'Plan pilihanmu': 'Your selected plan',
  'berlaku 30 hari': 'valid for 30 days',
  'Status pembayaran': 'Payment status',
  'Status pembayaran sedang diproses.': 'Payment status is being processed.',
  'Menyiapkan checkout QRIS.': 'Preparing QRIS checkout.',
  'Pembayaran QRIS berhasil diverifikasi.': 'QRIS payment was successfully verified.',
  'Bantuan Laprakin': 'Laprakin help',
  'Feedback pengguna': 'User feedback',
  'Kirim feedback': 'Send feedback',
  'Riwayat feedback': 'Feedback history',
  'Monitoring': 'Monitoring',
  'Risk review': 'Risk review',
  'CMS landing': 'Landing CMS',
  'Audit log': 'Audit log',
  'Retensi': 'Retention',
  'Admin console': 'Admin console',
  'Muat Admin Consoleâ€¦': 'Loading Admin Consoleâ€¦',
  'Coba muat ulang': 'Try reloading',
  'Muat ulang': 'Reload',
  'Privacy-first monitoring': 'Privacy-first monitoring',
  'User aktif': 'Active users',
  'Dokumen aktif': 'Active documents',
  'Job berjalan': 'Running jobs',
  'Feedback terbuka': 'Open feedback',
  'Risk terbuka': 'Open risks',
  'Aktivitas 7 hari': '7-day activity',
  'Job terbaru': 'Recent jobs',
  'Kejadian perlu ditinjau': 'Events requiring review',
  'Tinjau': 'Review',
  'Tutup': 'Close',
  'Landing CMS': 'Landing CMS',
  'Simpan CMS': 'Save CMS',
  'Pembersihan retensi': 'Retention cleanup',
  'Jalankan pembersihan': 'Run cleanup',
  'Akhiri semua sesi': 'End all sessions',
  'Ubah kata sandi': 'Change password',
  'Hapus akun': 'Delete account',
  'Unduh data saya': 'Download my data',
  'Izinkan AI eksternal': 'Allow external AI',
  'Kurangi animasi': 'Reduce motion',
  'Enter untuk kirim': 'Enter to send',
  'Gunakan Shift + Enter untuk membuat baris baru.': 'Use Shift + Enter to create a new line.',
  'Pengaturan akun': 'Account settings',
  'Projects': 'Projects',
  'Project baru': 'New project',
  'Cari project': 'Search projects',
  'Semua': 'All',
  'Dibuat oleh kamu': 'Created by you',
  'Dibagikan dengan kamu': 'Shared with you',
  'Nama': 'Name',
  'Diubah': 'Modifi÷}´æÚ$z{-®éÜj×vV6V¶âÖVævwVæ¶â7&VFVçF–Â6W'fW"âwÓÂ÷6ÖÆÃãÂöF—cãÇ7â6Æ74æÖS×¶–çFVw&F–öå7FGW3òævVÖ–æ“òæö³òw7FGW2Ö6ö×ÆWFVBs¦–çFVw&F–öå7FGW3òw7FGW2Öf–ÆVBs¢rwÓç¶–çFVw&F–öå7FGW3òævVÖ–æ“òæö³òw&VG’s¦–çFVw&F–öå7FGW3òv&VÇVÒ6–s¢v&VÇVÒF–6V²wÓÂ÷7ããÂö'F–6ÆSãÆ'F–6ÆSãÆF—cãÆ#ä§W&R&Æö"7F÷&vSÂö#ãÇ6ÖÆÃç¶–çFVw&F–öå7FGW3òæ§W&T&Æö#òæ6öçF–æW$æÖRò6öçF–æW#¢G¶–çFVw&F–öå7FGW2æ§W&T&Æö"æ6öçF–æW$æÖWÖ¢t6öçF–æW"FW'6Ö'VærVçGV²Fö·VÖVâVævwVæâwÓÂ÷6ÖÆÃãÂöF—cãÇ7â6Æ74æÖS×¶–çFVw&F–öå7FGW3òæ§W&T&Æö#òæö³òw7FGW2Ö6ö×ÆWFVBs¦–çFVw&F–öå7FGW3òw7FGW2Öf–ÆVBs¢rwÓç¶–çFVw&F–öå7FGW3òæ§W&T&Æö#òæö³òw&VG’s¦–çFVw&F–öå7FGW3òv&VÇVÒ6–s¢v&VÇVÒF–6V²wÓÂ÷7ããÂö'F–6ÆSãÂöF—cãÂ÷6V7F–öããÇ6V7F–öâ6Æ74æÖSÒ&FÖ–â×æVÂ#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂÖ†VB#ãÆƒ#åVÖ¶–âW"ÖöFVÃÂöƒ#ãÇ6ÖÆÃã3†&“Â÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–âÖÆ—7B#ç¶•W6vSòæ'&V¶F÷vãòæÆVæwFƒö•W6vRæ'&V¶F÷vâç6Æ–6RƒÃ’æÖ‚†—FVÒ“ÓãÆ'F–6ÆR¶W“×¶G¶—FVÒçW'÷6WÒÒG¶—FVÒæÖöFWÒÒG¶—FVÒæÖöFVÇÒÒG¶—FVÒç7FGW7ÖÓãÆF—cãÆ#ç¶—FVÒçW'÷6WÒ+r¶—FVÒæÖöFWÓÂö#ãÇ6ÖÆÃç¶—FVÒæÖöFVÇÒ+r´çVÖ&W"†—FVÒçF÷FÅ÷Fö¶Vç2ÇÂ’çFôÆö6ÆU7G&–ær‚v–BÔ”Br—ÒFö¶Vâ+r¶—FVÒæfW&vUöÆFVæ7•ö×2ÇÂÒ×3Â÷6ÖÆÃãÂöF—cãÇ7â6Æ74æÖS×¶7FGW2ÒG¶—FVÒç7FGW3ÓÓÒw7V66W72sòv6ö×ÆWFVBs¢vf–ÆVBwÖÓç¶—FVÒæ6ÆÇ7Ò6ÆÃÂ÷7ããÂö'F–6ÆSâ“£Çä&VÇVÒFVÖ¶–â’ãÂ÷çÓÂöF—cãÂ÷6V7F–öããÂöF—cãÂ÷6V7F–öãçĞ¢·F"ÓÓÒv–çFVw&F–öç2rbbÇ6V7F–öâ6Æ74æÖSÒ&FÖ–âÖ6öçFVçB#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂFÖ–â×v–FR#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂÖ†VB#ãÆƒ#åVÖ¶–â’W"W6W#Âöƒ#ãÇ6ÖÆÃäÖWFFF3†&’ÂFç&ö×BFâ÷WGWCÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–âÖÆ—7BFÖ–â×W6W"×W6vR#ç¶•W6vSòæ'•W6W#òæÆVæwF‚ò•W6vRæ'•W6W"æÖ‚†—FVÒ“ÓãÆ'F–6ÆR¶W“×¶—FVÒçW6W$–GÓãÆF—cãÆ#ç¶—FVÒægVÆÄæÖRÇÂ—FVÒæVÖ–ÇÓÂö#ãÇ6ÖÆÃç¶—FVÒæVÖ–ÇÒ+r¶—FVÒæW'&÷'7ÒW'&÷"+r&F×&F¶—FVÒæfW&vTÆFVæ7”×7Ò×3Â÷6ÖÆÃãÂöF—cãÇ7ãç¶—FVÒæ6ÆÇ7Ò6ÆÂ+r´çVÖ&W"†—FVÒçF÷FÅFö¶Vç2ÇÂ’çFôÆö6ÆU7G&–ær‚v–BÔ”Br—ÒFö¶VãÂ÷7ããÂö'F–6ÆSâ’¢Çä&VÇVÒFVÖ¶–âW"W6W"ãÂ÷çÓÂöF—cãÂöF—cãÂ÷6V7F–öãçĞ¢·F"ÓÓÒwWFFW2rbbÄfVGW&UWFFW4FÖ–â6WDæ÷F–6S×·6WDæ÷F–6WÒóçĞ¢·F"ÓÓÒvfVVF&6²rbbÇ6V7F–öâ6Æ74æÖSÒ&FÖ–âÖ6öçFVçB#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂFÖ–â×v–FR#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂÖ†VB#ãÆƒ#äfVVF&6²VævwVæÂöƒ#ãÇ6ÖÆÃå&VfW&Vç6’·VâF–æöæ–Ö¶âãÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–âÖÆ—7BfVVF&6²ÖFÖ–âÖÆ—7B#ç¶fVVF&6²æÆVæwF‚òfVVF&6²æÖ‚†—FVÒ’ÓâÆ'F–6ÆR¶W“×¶—FVÒæ–GÓãÆF—b6Æ74æÖSÒ&fVVF&6²ÖFÖ–âÖ&öG’#ãÆF—cãÆ#ç¶—FVÒæ6FVv÷'—Ò+r¶—FVÒç&F–ærÇÂ~(	BwÒóSÂö#ãÇ6ÖÆÃç¶—FVÒçW6W%&VgÒ+r¶f÷&ÖDFFR†—FVÒçWFFVDB—ÓÂ÷6ÖÆÃãÂöF—cãÇç¶—FVÒæ&öG—ÓÂ÷ç¶—FVÒç&WÆ–W3òæÖ‚†—FVÕ&WÇ’’ÓâÇ6ÖÆÂ¶W“×¶—FVÕ&WÇ’æ–GÒ6Æ74æÖSÒ&FÖ–â×&WÇ’#åF–Ó¢¶—FVÕ&WÇ’æ&öG—ÓÂ÷6ÖÆÃâ—ÓÆF—b6Æ74æÖSÒ&FÖ–âÖ–æÆ–æR#ãÆ–çWBfÇVS×·&WÇ•¶—FVÒæ–EÒÇÂrwÒöä6†ævS×²†WfVçB’Óâ6WE&WÇ’‚‡&Wb“Óâ‡²ââç&WbÅ¶—FVÒæ–EÓ¦WfVçBçF&vWBçfÇVWÒ’—ÒÆ6V†öÆFW#Ò%GVÆ—2&Æ6âVçGV²W6W"âââ"óãÄ'WGFöâöä6Æ–6³×²‚’Óâ6VæE&WÇ’†—FVÒæ–B—ÒF—6&ÆVC×¶'W7—Óä¶—&–ÓÂô'WGFöããÂöF—cãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–âÖ7F–öç2#ãÄ7W7FöÕ6VÆV7BfÇVS×¶—FVÒç7FGW7Òöä6†ævS×²‡fÇVR’ÓâWFFTfVVF&6²†—FVÒæ–BÂfÇVR—Ò÷F–öç3×µ··fÇVS¢v÷VârÆÆ&VÃ¢t÷VâwÒÇ·fÇVS¢w&Wf–Wv–ærrÆÆ&VÃ¢u&Wf–Wv–ærwÒÇ·fÇVS¢w&W6öÇfVBrÆÆ&VÃ¢u&W6öÇfVBwÒÇ·fÇVS¢v6Æ÷6VBrÆÆ&VÃ¢t6Æ÷6VBwÕ×ÒóãÂöF—cãÂö'F–6ÆSâ’¢Ç6Æ74æÖSÒ&V×G’ÖFÖ–â#ä&VÇVÒFfVVF&6²ãÂ÷çÓÂöF—cãÂöF—cãÂ÷6V7F–öãçĞ¢·F"ÓÓÒw&—6²rbbÇ6V7F–öâ6Æ74æÖSÒ&FÖ–âÖ6öçFVçB#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂFÖ–â×v–FR#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂÖ†VB#ãÆƒ#ä¶V¦F–âW&ÇRF—F–æ¦SÂöƒ#ãÇ6ÖÆÃåF–F²÷FöÖF—2ÖVçVGV‚FRÖVÖ&Æö¶—"·VâãÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–âÖÆ—7B#ç¶÷fW'f–WræWfVçG3òæÆVæwF‚ò÷fW'f–WræWfVçG2æÖ‚†WfVçB’ÓâÆ'F–6ÆR¶W“×¶WfVçBæ–GÓãÆF—cãÆ#ç¶WfVçBç7VÖÖ'—ÓÂö#ãÇ6ÖÆÃç¶WfVçBçW6W%&VgÒ+r¶WfVçBæ6FVv÷'—Ò+r¶WfVçBç6WfW&—G—Ò+r¶f÷&ÖDFFR†WfVçBæ7&VFVDB—ÓÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–â×&—6²Ö7F–öç2#ãÇ7â6Æ74æÖS×¶&—6²ÒG¶WfVçBç7FGW7ÖÓç¶WfVçBç7FGW7ÓÂ÷7ãç¶WfVçBç7FGW2ÓÓÒv÷VârbbÃãÆ'WGFöâöä6Æ–6³×²‚’Óâ&Wf–Wu&—6²†WfVçBæ–BÂw&Wf–WvVBr—ÓåF–æ¦SÂö'WGFöããÆ'WGFöâöä6Æ–6³×²‚’Óâ&Wf–Wu&—6²†WfVçBæ–BÂvF—6Ö—76VBr—ÓåGWGWÂö'WGFöããÂóçÓÂöF—cãÂö'F–6ÆSâ’¢Ç6Æ74æÖSÒ&V×G’ÖFÖ–â#ä&VÇVÒF¶V¦F–â–ærW&ÇRF—F–æ¦RãÂ÷çÓÂöF—cãÂöF—cãÂ÷6V7F–öãçĞ¢·F"ÓÓÒv6×2rbbÇ6V7F–öâ6Æ74æÖSÒ&FÖ–âÖ6öçFVçB#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂFÖ–â×v–FR#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂÖ†VB#ãÆƒ#äÆæF–ær4Õ3Âöƒ#ãÇ6ÖÆÃäGW"FV·2ÂFW7F–Ööæ’&W&—¦–âÂFâf—7VÂÆæF–ærãÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&6×2Öf÷&Ò#ãÅFövvÆR6†V6¶VC×´&ööÆVâ†ÆæF–æræææ÷Væ6VÖVçCòæVæ&ÆVB—Òöä6†ævS×²†6†V6¶VB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆææ÷Væ6VÖVçC§²ââç&Wbæææ÷Væ6VÖVçBÆVæ&ÆVC¦6†V6¶VG×Ò’—ÒF—FÆSÒ%F×–Æ¶âææ÷Væ6VÖVçB"FW67&—F–öãÒ$×Væ7VÂF’&v–âF2†W&òâ"óãÆÆ&VÃåFV·2ææ÷Væ6VÖVçCÆ–çWBfÇVS×¶ÆæF–æræææ÷Væ6VÖVçCòçFW‡BÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆææ÷Væ6VÖVçC§²ââç&Wbæææ÷Væ6VÖVçBÇFW‡C¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ#ƒ"óãÂöÆ&VÃãÆÆ&VÃä5Dææ÷Væ6VÖVçCÆ–çWBfÇVS×¶ÆæF–æræææ÷Væ6VÖVçCòæ7FÆ&VÂÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆææ÷Væ6VÖVçC§²ââç&Wbæææ÷Væ6VÖVçBÆ7FÆ&VÃ¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ#3""óãÂöÆ&VÃãÆF—b6Æ74æÖSÒ&6×2Ö6÷’×6V7F–öâ#ãÆF—cãÆ#ä6÷’ÆæF–æsÂö#ãÇ6ÖÆÃåV&‚§VGVÂFâFV·2WFÖÆæF–ærFçÖVç–VçGV‚Æ–÷WBãÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&6×2Ö6÷’Öw&–B#ãÆÆ&VÃä§VGVÂ†W&óÆ–çWBfÇVS×¶ÆæF–æræ6÷“òæ†W&õF—FÆRÇÂtÆ&¶–âwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Æ†W&õF—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ#c"óãÂöÆ&VÃãÆÆ&VÃäFW6·&—6’†W&óÇFW‡F&VfÇVS×¶ÆæF–æræ6÷“òæ†W&õ7V'F—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Æ†W&õ7V'F—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##ƒ"óãÂöÆ&VÃãÆÆ&VÃä§VGVÂÆ–æãÆ–çWBfÇVS×¶ÆæF–æræ6÷“òç6W'f–6W5F—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Ç6W'f–6W5F—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##"óãÂöÆ&VÃãÆÆ&VÃäFW6·&—6’Æ–æãÇFW‡F&VfÇVS×¶ÆæF–æræ6÷“òç6W'f–6W57V'F—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Ç6W'f–6W57V'F—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##ƒ"óãÂöÆ&VÃãÆÆ&VÃä§VGVÂW&&VFãÆ–çWBfÇVS×¶ÆæF–æræ6÷“òæ6ö×&UF—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Æ6ö×&UF—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##"óãÂöÆ&VÃãÆÆ&VÃäFW6·&—6’W&&VFãÇFW‡F&VfÇVS×¶ÆæF–æræ6÷“òæ6ö×&U7V'F—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Æ6ö×&U7V'F—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##ƒ"óãÂöÆ&VÃãÆÆ&VÃä§VGVÂGWF÷&–ÃÆ–çWBfÇVS×¶ÆæF–æræ6÷“òçGWF÷&–ÅF—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’ÇGWF÷&–ÅF—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##"óãÂöÆ&VÃãÆÆ&VÃäFW6·&—6’GWF÷&–ÃÇFW‡F&VfÇVS×¶ÆæF–æræ6÷“òçGWF÷&–Å7V'F—FÆRÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’ÇGWF÷&–Å7V'F—FÆS¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##ƒ"óãÂöÆ&VÃãÆÆ&VÃäFW6·&—6’fö÷FW#ÇFW‡F&VfÇVS×¶ÆæF–æræ6÷“òæfö÷FW%FW‡BÇÂrwÒöä6†ævS×²†WfVçB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÆ6÷“§²âââ‡&Wbæ6÷’ÇÂ·Ò’Æfö÷FW%FW‡C¦WfVçBçF&vWBçfÇVW×Ò’—ÒÖ„ÆVæwFƒÒ##ƒ"óãÂöÆ&VÃãÂöF—cãÂöF—cãÆF—b6Æ74æÖSÒ&6×2ÖÖVF–Öw&–B6×2ÖÖVF–Öw&–BÖW‡æFVB#à¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ävÖ&"ÆF"†W&óÂö#ãÇ6ÖÆÃä÷6–öæÂâärÂ¥rÂFRtT%âw&F–VçBFWFÖVæ¦vFV·2†W&òFW&&6ãÂ÷6ÖÆÃãÆF—b6Æ74æÖSÒ&6×2ÖÖVF–×&Wf–Wr#ç¶ÆæF–æræÖVF–òæ†W&ô–ÖvUW&ÂòÆ–Ör7&3×¶ÆæF–æræÖVF–æ†W&ô–ÖvUW&ÇÒÇCÒ%&Wf–Wr†W&ò"óâ¢t&VÇVÒFvÖ&"wÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&–ÖvR÷ærÆ–ÖvRö§VrÆ–ÖvR÷vV'"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv†W&òr—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ†W&ô–ÖvUW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶†W&ô–ÖvUW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂvÖ&""óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ä6ö×&R&6–2(	B’Æ–ãÂö#ãÇ6ÖÆÃåDb6—6’¶—&’VçGV²F"&6–2ãÂ÷6ÖÆÃãÆF—b6Æ74æÖS×¶6×2ÖÖVF–×&Wf–WrG²†ÆæF–æræÖVF–òæ6ö×&T&6–4•FeW&ÂÇÂÆæF–æræÖVF–òæ6ö×&T•FeW&Â’òwFbr¢rwÖÓç²†ÆæF–æræÖVF–òæ6ö×&T&6–4•FeW&ÂÇÂÆæF–æræÖVF–òæ6ö×&T•FeW&Â’òuDbFW'6Ö'Værr¢u¶’DbFVÖò&vâwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&Æ–6F–öâ÷Fb"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&RÖ&6–2Ö’r—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&T&6–4•FeW&ÂÇÂÆæF–æræÖVF–òæ6ö×&T•FeW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&T•FeW&Ã¦WfVçBçF&vWBçfÇVRÆ6ö×&T&6–4•FeW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂDb"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ä6ö×&R&6–2(	BÆ&¶–ãÂö#ãÇ6ÖÆÃåDb6—6’¶æâVçGV²F"&6–2ãÂ÷6ÖÆÃãÆF—b6Æ74æÖS×¶6×2ÖÖVF–×&Wf–WrG²†ÆæF–æræÖVF–òæ6ö×&T&6–4Æ&¶–åFeW&ÂÇÂÆæF–æræÖVF–òæ6ö×&TÆ&¶–åFeW&Â’òwFbr¢rwÖÓç²†ÆæF–æræÖVF–òæ6ö×&T&6–4Æ&¶–åFeW&ÂÇÂÆæF–æræÖVF–òæ6ö×&TÆ&¶–åFeW&Â’òuDbFW'6Ö'Værr¢u¶’DbFVÖò&vâwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&Æ–6F–öâ÷Fb"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&RÖ&6–2ÖÆ&¶–âr—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&T&6–4Æ&¶–åFeW&ÂÇÂÆæF–æræÖVF–òæ6ö×&TÆ&¶–åFeW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&TÆ&¶–åFeW&Ã¦WfVçBçF&vWBçfÇVRÆ6ö×&T&6–4Æ&¶–åFeW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂDb"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ä6ö×&RF†–æ¶–ær(	B’Æ–ãÂö#ãÇ6ÖÆÃåDb6—6’¶—&’VçGV²F"F†–æ¶–ærãÂ÷6ÖÆÃãÆF—b6Æ74æÖS×¶6×2ÖÖVF–×&Wf–WrG¶ÆæF–æræÖVF–òæ6ö×&UF†–æ¶–æt•FeW&ÂòwFbr¢rwÖÓç¶ÆæF–æræÖVF–òæ6ö×&UF†–æ¶–æt•FeW&ÂòuDbFW'6Ö'Værr¢t&VÇVÒFDbwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&Æ–6F–öâ÷Fb"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&R×F†–æ¶–ærÖ’r—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&UF†–æ¶–æt•FeW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&UF†–æ¶–æt•FeW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂDb"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ä6ö×&RF†–æ¶–ær(	BÆ&¶–ãÂö#ãÇ6ÖÆÃåDb6—6’¶æâVçGV²F"F†–æ¶–ærãÂ÷6ÖÆÃãÆF—b6Æ74æÖS×¶6×2ÖÖVF–×&Wf–WrG¶ÆæF–æræÖVF–òæ6ö×&UF†–æ¶–ætÆ&¶–åFeW&ÂòwFbr¢rwÖÓç¶ÆæF–æræÖVF–òæ6ö×&UF†–æ¶–ætÆ&¶–åFeW&ÂòuDbFW'6Ö'Værr¢t&VÇVÒFDbwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&Æ–6F–öâ÷Fb"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&R×F†–æ¶–ærÖÆ&¶–âr—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&UF†–æ¶–ætÆ&¶–åFeW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&UF†–æ¶–ætÆ&¶–åFeW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂDb"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ä6ö×&R‡G&F†–æ²(	B’Æ–ãÂö#ãÇ6ÖÆÃåDb6—6’¶—&’VçGV²F"‡G&F†–æ²ãÂ÷6ÖÆÃãÆF—b6Æ74æÖS×¶6×2ÖÖVF–×&Wf–WrG¶ÆæF–æræÖVF–òæ6ö×&U‡G&F†–æ´•FeW&ÂòwFbr¢rwÖÓç¶ÆæF–æræÖVF–òæ6ö×&U‡G&F†–æ´•FeW&ÂòuDbFW'6Ö'Værr¢t&VÇVÒFDbwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&Æ–6F–öâ÷Fb"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&R×‡G&F†–æ²Ö’r—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&U‡G&F†–æ´•FeW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&U‡G&F†–æ´•FeW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂDb"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B#ãÆ#ä6ö×&R‡G&F†–æ²(	BÆ&¶–ãÂö#ãÇ6ÖÆÃåDb6—6’¶æâVçGV²F"‡G&F†–æ²ãÂ÷6ÖÆÃãÆF—b6Æ74æÖS×¶6×2ÖÖVF–×&Wf–WrG¶ÆæF–æræÖVF–òæ6ö×&U‡G&F†–æ´Æ&¶–åFeW&ÂòwFbr¢rwÖÓç¶ÆæF–æræÖVF–òæ6ö×&U‡G&F†–æ´Æ&¶–åFeW&ÂòuDbFW'6Ö'Værr¢t&VÇVÒFDbwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ&Æ–6F–öâ÷Fb"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&R×‡G&F†–æ²ÖÆ&¶–âr—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&U‡G&F†–æ´Æ&¶–åFeW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&U‡G&F†–æ´Æ&¶–åFeW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$ÂDb"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B6×2×f–FVòÖ6&B#ãÆ#åf–FVòW&&æF–ævãÂö#ãÇ6ÖÆÃäÕBFRtT$Ò–ærÖVÖ&æF–æv¶â’V×VÒFVævâÆ&¶–âFÆÒ6GRf–FVòãÂ÷6ÖÆÃãÆF—b6Æ74æÖSÒ&6×2ÖÖVF–×&Wf–Wr#ç¶ÆæF–æræÖVF–òæ6ö×&Uf–FVõW&ÂòÇf–FVò7&3×¶ÆæF–æræÖVF–æ6ö×&Uf–FVõW&ÇÒ×WFVBÆ—4–æÆ–æR&VÆöCÒ&ÖWFFF"óâ¢t&VÇVÒFf–FVòwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ'f–FVòö×BÇf–FVò÷vV&Ò"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂv6ö×&R×f–FVòr—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òæ6ö×&Uf–FVõW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡¶6ö×&Uf–FVõW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$Âf–FVò"óãÂö'F–6ÆSà¢Æ'F–6ÆR6Æ74æÖSÒ&6×2ÖÖVF–Ö6&B6×2×f–FVòÖ6&B#ãÆ#åf–FVò&öGV7BFVÖóÂö#ãÇ6ÖÆÃäÕBFRtT$ÒâF—WF"÷FöÖF—2F’†W&òFç7V&Fâ&W'VÆærãÂ÷6ÖÆÃãÆF—b6Æ74æÖSÒ&6×2ÖÖVF–×&Wf–Wr#ç¶ÆæF–æræÖVF–òçGWF÷&–Åf–FVõW&ÂòÇf–FVò7&3×¶ÆæF–æræÖVF–çGWF÷&–Åf–FVõW&ÇÒ×WFVBÆ—4–æÆ–æR&VÆöCÒ&ÖWFFF"óâ¢t&VÇVÒFf–FVòwÓÂöF—cãÆ–çWBG—SÒ&f–ÆR"66WCÒ'f–FVòö×BÇf–FVò÷vV&Ò"öä6†ævS×²†WfVçB“ÓçWÆöDÆæF–ætÖVF–†WfVçBÂwGWF÷&–Â×f–FVòr—ÒF—6&ÆVC×¶'W7—ÒóãÆ–çWBfÇVS×¶ÆæF–æræÖVF–òçGWF÷&–Åf–FVõW&ÂÇÂrwÒöä6†ævS×²†WfVçB“ÓçWFFTÆæF–ætÖVF–‡·GWF÷&–Åf–FVõW&Ã¦WfVçBçF&vWBçfÇVWÒ—ÒÆ6V†öÆFW#Ò$FRFV×VÂU$Âf–FVò"óãÂö'F–6ÆSà£ÂöF—cãÆF—b6Æ74æÖSÒ&6×2×FW7F–Ööæ–Ç2#ãÆ#åFW7F–Ööæ“Âö#ç²†ÆæF–ærçFW7F–Ööæ–Ç2ÇÂµÒ’æÆVæwF‚òÆæF–ærçFW7F–Ööæ–Ç2æÖ‚†—FVÒÆ–æFW‚“ÓãÆ'F–6ÆR¶W“×¶—FVÒæ–BÇÂ–æFW‡ÓãÆF—cãÆ#ç¶—FVÒææÖWÓÂö#ãÇ6ÖÆÃç¶—FVÒæÆ&VÇÓÂ÷6ÖÆÃãÇç¶—FVÒçV÷FWÓÂ÷ãÂöF—cãÅFövvÆR6†V6¶VC×´&ööÆVâ†—FVÒçV&Æ—6†VB—Òöä6†ævS×²†6†V6¶VB“Óç6WDÆæF–ær‚‡&Wb“Óâ‡²ââç&WbÇFW7F–Ööæ–Ç3§&WbçFW7F–Ööæ–Ç2æÖ‚‡&÷rÆ’“Óæ“ÓÓÖ–æFWƒ÷²ââç&÷rÇV&Æ—6†VC¦6†V6¶VGÓ§&÷r—Ò’—ÒF—FÆSÒ%V&Æ—6‚"óãÂö'F–6ÆSâ’¢Ç6Æ74æÖSÒ&×WFVBÖæ÷FR#ä&VÇVÒFFW7F–Ööæ’&W&—¦–âãÂ÷çÓÂöF—cãÄ'WGFöâöä6Æ–6³×·6fTÆæF–æwÒF—6&ÆVC×¶'W7—ÓãÅ6fR6—¦S×³GÒóå6–×â4Õ3Âô'WGFöããÂöF—cãÂöF—cãÂ÷6V7F–öãçĞ¢·F"ÓÓÒvVF—BrbbÇ6V7F–öâ6Æ74æÖSÒ&FÖ–âÖ6öçFVçB#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂFÖ–â×v–FR#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂÖ†VB#ãÆƒ#äVF—BÆösÂöƒ#ãÇ6ÖÆÃäÖWFFFWfVçBÂFç—6’6†Böf–ÆRãÂ÷6ÖÆÃãÂöF—cãÆF—b6Æ74æÖSÒ&FÖ–âÖÆ—7B#ç¶VF—BæÖ‚†WfVçB“ÓãÆ'F–6ÆR¶W“×¶WfVçBæ–GÓãÆF—cãÆ#ç¶WfVçBæ7F–öçÓÂö#ãÇ6ÖÆÃç¶WfVçBæ7F÷%&VgÒ+r¶WfVçBçF&vWEG—WÒ+r¶f÷&ÖDFFR†WfVçBæ7&VFVDB—ÓÂ÷6ÖÆÃãÂöF—cãÂö'F–6ÆSâ—ÓÂöF—cãÂöF—cãÂ÷6V7F–öãçĞ¢·F"ÓÓÒw&WFVçF–öârbbÇ6V7F–öâ6Æ74æÖSÒ&FÖ–âÖ6öçFVçB#ãÆF—b6Æ74æÖSÒ&FÖ–â×æVÂFÖ–â×v–FR&WFVçF–öâ×æVÂ#ãÄf–ÆT6ör6—¦S×³#GÒóãÆƒ#åVÖ&W'6–†â&WFVç6“Âöƒ#ãÇäÖVæv†W2&W6÷W&6R6VÖVçF&FRÖVÆWvF’Ö6&WFVç6’6W7V’¶V&–¦¶ââF–F²ÖVÖ&6—6’f–ÆRVævwVæãÂ÷ãÄ'WGFöâöä6Æ–6³×·'Vå&WFVçF–öçÒF—6&ÆVC×¶'W7—ÓãÅ&Vg&W6„7r6—¦S×³GÒóä¦Ææ¶âVÖ&W'6–†ãÂô'WGFöããÂöF—cãÂ÷6V7F–öãçĞ¢ÂöÖ–ãà¢ÂöF—cã°§Ğ ¦gVæ7F–öâÆöF–æu67&VVâ‚’²&WGW&âÆF—b6Æ74æÖSÒ&ÆöF–ær×67&VVâ#ãÄÆöFW$6—&6ÆR6Æ74æÖSÒ'7–â"6—¦S×³#ÒóãÇ7ãäÖVç––¶âÆ&¶–âââãÂ÷7ããÂöF—cã²Ğ ¦7&VFU&ö÷B†Fö7VÖVçBævWDVÆVÖVçD'”–B‚w&ö÷Br’’ç&VæFW"ƒÄ'&÷w6W%&÷WFW#ãÄóãÂô'&÷w6W%&÷WFW#â“° 