import { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, FlaskConical, Gauge, Play, Power, ShieldCheck } from 'lucide-react';
import CustomSelect from '../../../components/CustomSelect';
import { AdminResource, ConfirmationDialog, EmptyState, PageIntro, StatusPill, useAdminAi, useAdminAiCopy, useAdminResource } from './shared';

const metric = (value, suffix = '') => value === null || value === undefined ? '—' : `${Number(value).toLocaleString()}${suffix}`;
const percentage = (value) => `${(Number(value || 0) * 100).toFixed(1)}%`;

export default function HealthModule() {
  const { client, affordances } = useAdminAi();
  const t = useAdminAiCopy();
  const [days, setDays] = useState(7);
  const [revisionId, setRevisionId] = useState('');
  const [target, setTarget] = useState({ providerId: '', modelId: '' });
  const [maintenanceMessage, setMaintenanceMessage] = useState('');
  const [busy, setBusy] = useState('');
  const [dialog, setDialog] = useState('');
  const [actionResult, setActionResult] = useState(null);
  const [actionError, setActionError] = useState('');
  const load = useCallback(() => client.health(days), [client, days]);
  const resource = useAdminResource(load);
  useEffect(() => {
    if (!revisionId && resource.data?.runtime?.available && resource.data.runtime.revisionId) setRevisionId(resource.data.runtime.revisionId);
  }, [resource.data?.runtime?.available, resource.data?.runtime?.revisionId, revisionId]);
  useEffect(() => { setMaintenanceMessage(resource.data?.maintenance?.message || ''); }, [resource.data?.maintenance?.message]);
  const run = async (kind) => {
    setBusy(kind); setActionError(''); setActionResult(null);
    try {
      const result = kind === 'test' ? await client.testRevision(revisionId.trim()) : await client.canary(revisionId.trim());
      setActionResult({ kind, result }); await resource.retry();
    } catch (error) { setActionError(error.message); }
    finally { setBusy(''); }
  };
  const confirmControl = async ({ reason, confirmation }) => {
    setBusy(dialog); setActionError('');
    try {
      if (dialog === 'open' || dialog === 'clear') {
        const body = { revisionId: revisionId.trim(), providerId: target.providerId.trim(), modelId: target.modelId.trim(), reason, confirmation };
        if (dialog === 'open') await client.openCircuit(body);
        else await client.clearCircuit(body);
      } else {
        const enabled = dialog === 'maintenance-enable';
        await client.updateMaintenance({ enabled, message: enabled ? maintenanceMessage.trim() : '', reason, confirmation });
      }
      setActionResult({ kind: dialog }); setDialog(''); await resource.retry();
    } finally { setBusy(''); }
  };
  const expected = dialog === 'open' ? `OPEN CIRCUIT ${target.providerId}:${target.modelId}`
    : dialog === 'clear' ? `CLEAR CIRCUIT ${target.providerId}:${target.modelId}`
      : dialog === 'maintenance-enable' ? 'ENABLE AI MAINTENANCE' : 'CLEAR AI MAINTENANCE';
  return <>
    <PageIntro title={t('health.title')} description={t('health.description')} resource={resource} actions={<label className="admin-ai-days">{t('health.range')}<CustomSelect ariaLabel={t('health.range')} value={String(days)} onChange={(value) => setDays(Number(value))} options={[{ value: '1', label: t('health.day') }, { value: '7', label: t('health.days7') }, { value: '30', label: t('health.days30') }, { value: '90', label: t('health.days90') }]} /></label>} />
    <AdminResource resource={resource} label={t('health.loadLabel')}>{(data) => <>
      <div className="admin-ai-health-grid"><article><ShieldCheck size={17} /><span>{t('health.runtimeSource')}</span><b>{data.runtime?.source || t('common.status.unavailable')}</b><small>{data.runtime?.revisionId || t('health.noActive')}</small></article><article><Activity size={17} /><span>{t('health.textReadiness')}</span><b>{data.readiness?.textReady ? t('health.ready') : t('models.unavailable')}</b><StatusPill value={data.readiness?.textReady ? 'healthy' : 'unavailable'} /></article><article><FlaskConical size={17} /><span>{t('health.visionReadiness')}</span><b>{data.readiness?.visionReady ? t('health.ready') : t('models.unavailable')}</b><StatusPill value={data.readiness?.visionReady ? 'healthy' : 'unavailable'} /></article><article><Gauge size={17} /><span>{t('health.providerModel')}</span><b>{data.runtime?.providers?.length || 0} / {data.runtime?.models?.length || 0}</b><small>{data.runtime?.available ? t('health.runtimeReady') : data.runtime?.degradedReason || t('health.runtimeUnavailable')}</small></article></div>
      <div className="admin-ai-health-grid admin-ai-metric-grid"><article><Gauge size={17} /><span>{t('health.latencyPercentiles')}</span><b>{metric(data.summary?.latencyP50Ms, ' ms')} / {metric(data.summary?.latencyP95Ms, ' ms')}</b><small>p50 / p95</small></article><article><Activity size={17} /><span>{t('health.firstTokenPercentiles')}</span><b>{metric(data.summary?.firstTokenP50Ms, ' ms')} / {metric(data.summary?.firstTokenP95Ms, ' ms')}</b><small>{t('health.requestRate', { rate: metric(data.summary?.requestRatePerMinute) })}</small></article><article><ShieldCheck size={17} /><span>{t('health.successFallback')}</span><b>{percentage(data.summary?.successRate)} / {percentage(data.summary?.fallbackRate)}</b><small>{t('health.callQueue', { calls: data.summary?.calls || 0, queue: data.summary?.maximumQueueDepth || 0 })}</small></article><article><AlertTriangle size={17} /><span>{t('health.operationalErrors')}</span><b>{Number(data.summary?.rateLimitErrors || 0)} / {Number(data.summary?.authErrors || 0)} / {Number(data.summary?.timeoutErrors || 0)}</b><small>{t('health.errorOrder')}</small></article></div>
      <section className="admin-ai-panel"><div className="admin-ai-panel-heading"><div><p>{t('health.telemetry')}</p><h2>{t('health.traffic')}</h2></div><span>{t('health.period', { days: data.days })}</span></div>{data.telemetry?.length ? <div className="admin-ai-table-wrap"><table className="admin-ai-table"><thead><tr><th>{t('health.route')}</th><th>{t('health.providerModel')}</th><th>{t('providers.status')}</th><th>{t('health.calls')}</th><th>{t('health.latency')}</th><th>{t('health.tokens')}</th><th>{t('health.fallbackQueue')}</th></tr></thead><tbody>{data.telemetry.map((row, index) => <tr key={`${row.configuration_revision}:${row.route_id}:${row.provider}:${row.model}:${row.status}:${index}`}><td><b>{row.route_id || t('common.unknown')}</b><small>{row.mode || t('health.defaultMode')}</small></td><td>{row.provider || t('common.notAvailable')}<small>{row.model || t('common.notAvailable')}</small></td><td><StatusPill value={row.status || row.circuit_state} /></td><td>{Number(row.calls || 0).toLocaleString()}</td><td>{Number(row.average_latency_ms || 0).toLocaleString()} ms</td><td>{Number(row.total_tokens || 0).toLocaleString()}</td><td>{Number(row.fallbacks || 0)} / {Number(row.maximum_queue_depth || 0)}</td></tr>)}</tbody></table></div> : <EmptyState title={t('health.noTelemetry')} description={t('health.noTelemetryDescription')} />}</section>
      <div className="admin-ai-detail-grid"><section className="admin-ai-panel"><div className="admin-ai-panel-heading"><div><p>{t('health.routeHealth')}</p><h2>{t('health.routeReliability')}</h2></div><StatusPill value={data.summary?.circuitState || 'closed'} /></div>{data.routeHealth?.length ? <div className="admin-ai-table-wrap"><table className="admin-ai-table"><thead><tr><th>{t('health.route')}</th><th>{t('health.success')}</th><th>{t('health.latency')}</th><th>{t('health.circuit')}</th></tr></thead><tbody>{data.routeHealth.map((row) => <tr key={row.routeId}><td>{row.routeId}</td><td>{percentage(row.successRate)}</td><td>{metric(row.latencyP50Ms, ' ms')} / {metric(row.latencyP95Ms, ' ms')}</td><td><StatusPill value={row.circuitState} /></td></tr>)}</tbody></table></div> : <EmptyState title={t('health.noRoutes')} description={t('health.noRoutesDescription')} />}</section><section className="admin-ai-panel"><div className="admin-ai-panel-heading"><div><p>{t('health.modelAvailability')}</p><h2>{t('health.modelStatus')}</h2></div><span>{data.latestConfigurationChange ? t('health.latestRevision', { number: data.latestConfigurationChange.revisionNumber }) : t('common.notAvailable')}</span></div>{data.modelAvailability?.length ? <div className="admin-ai-table-wrap"><table className="admin-ai-table"><thead><tr><th>{t('health.providerModel')}</th><th>{t('providers.status')}</th><th>{t('health.lastAvailable')}</th></tr></thead><tbody>{data.modelAvailability.map((row) => <tr key={`${row.providerId}:${row.modelId}`}><td>{row.providerId}<small>{row.modelId}</small></td><td><StatusPill value={row.available ? row.health || 'available' : 'unavailable'} /></td><td>{row.lastAvailableAt ? new Date(row.lastAvailableAt).toLocaleString() : t('common.notAvailable')}</td></tr>)}</tbody></table></div> : <EmptyState title={t('health.noModels')} description={t('health.noModelsDescription')} />}</section></div>
    </>}</AdminResource>
    {(affordances.manageProviders || affordances.viewHealth) && <section className="admin-ai-action-panel"><div><p>{t('health.validation')}</p><h2>{t('health.testTitle')}</h2><span>{t('health.synthetic')}</span></div><label>{t('common.revision')}<input aria-label={t('common.revision')} value={revisionId} onChange={(event) => setRevisionId(event.target.value)} placeholder="ai-config-…" /></label><div className="admin-ai-action-buttons">{affordances.viewHealth && <button type="button" onClick={() => run('canary')} disabled={!revisionId.trim() || Boolean(busy)}><FlaskConical size={14} /> {busy === 'canary' ? t('health.running') : t('health.runCanary')}</button>}{affordances.manageProviders && <button className="admin-ai-primary-action" type="button" onClick={() => run('test')} disabled={!revisionId.trim() || Boolean(busy)}><Play size={14} /> {busy === 'test' ? t('health.testing') : t('health.testRevision')}</button>}</div></section>}
    {affordances.manageRouting && <section className="admin-ai-action-panel admin-ai-control-panel"><div><p>{t('health.circuitControl')}</p><h2>{t('health.circuitTitle')}</h2><span>{t('health.circuitDescription')}</span></div><div className="admin-ai-control-fields"><label>{t('providers.providerId')}<input aria-label={t('health.circuitProvider')} value={target.providerId} onChange={(event) => setTarget((value) => ({ ...value, providerId: event.target.value }))} /></label><label>{t('models.modelId')}<input aria-label={t('health.circuitModel')} value={target.modelId} onChange={(event) => setTarget((value) => ({ ...value, modelId: event.target.value }))} /></label></div><div className="admin-ai-action-buttons"><button type="button" onClick={() => setDialog('clear')} disabled={!revisionId.trim() || !target.providerId.trim() || !target.modelId.trim() || Boolean(busy)}>{t('health.clearCircuit')}</button><button className="admin-ai-emergency" type="button" onClick={() => setDialog('open')} disabled={!revisionId.trim() || !target.providerId.trim() || !target.modelId.trim() || Boolean(busy)}><Power size={14} /> {t('health.openCircuit')}</button></div><div className="admin-ai-circuit-list">{resource.data?.circuits?.length ? resource.data.circuits.map((item) => <span key={`${item.providerId}:${item.modelId}`}><code>{item.providerId}:{item.modelId}</code><StatusPill value={item.state} /></span>) : <small>{t('health.noOpenCircuits')}</small>}</div></section>}
    {affordances.manageRouting && <section className="admin-ai-action-panel admin-ai-control-panel"><div><p>{t('health.maintenance')}</p><h2>{t('health.maintenanceTitle')}</h2><span>{resource.data?.maintenance?.enabled ? t('health.maintenanceActive') : t('health.maintenanceInactive')}</span></div><label>{t('health.maintenanceMessage')}<textarea aria-label={t('health.maintenanceMessage')} value={maintenanceMessage} onChange={(event) => setMaintenanceMessage(event.target.value)} maxLength="500" /></label><div className="admin-ai-action-buttons">{resource.data?.maintenance?.enabled && <button type="button" onClick={() => setDialog('maintenance-clear')} disabled={Boolean(busy)}>{t('health.clearMaintenance')}</button>}<button className="admin-ai-emergency" type="button" onClick={() => setDialog('maintenance-enable')} disabled={Boolean(busy) || maintenanceMessage.trim().length < 8}><AlertTriangle size={14} /> {t('health.enableMaintenance')}</button></div></section>}
    {actionError && <div className="admin-ai-inline-error" role="alert">{actionError}</div>}
    {actionResult && <div className="admin-ai-success" role="status"><ShieldCheck size={15} /><span>{actionResult.kind === 'test' ? t('health.tested', { id: actionResult.result.revision?.id }) : actionResult.kind === 'canary' ? t('health.canaryDone', { count: actionResult.result.results?.length || 0 }) : t('health.controlSaved')}</span></div>}
    <ConfirmationDialog open={Boolean(dialog)} title={dialog === 'open' ? t('health.openCircuitTitle') : dialog === 'clear' ? t('health.clearCircuitTitle') : dialog === 'maintenance-enable' ? t('health.enableMaintenanceTitle') : t('health.clearMaintenanceTitle')} description={dialog === 'open' ? t('health.openCircuitDescription') : dialog === 'clear' ? t('health.clearCircuitDescription') : dialog === 'maintenance-enable' ? t('health.enableMaintenanceDescription') : t('health.clearMaintenanceDescription')} expected={expected} confirmLabel={dialog === 'open' ? t('health.openCircuit') : dialog === 'clear' ? t('health.clearCircuit') : dialog === 'maintenance-enable' ? t('health.enableMaintenance') : t('health.clearMaintenance')} busy={Boolean(busy)} onCancel={() => setDialog('')} onConfirm={confirmControl} />
  </>;
}
